name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this solve? What's your use case?
      placeholder: I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: What part of the codebase would this affect?
      options:
        - CLI / Arguments
        - Client mode
        - Server mode
        - Daemon mode / REST API
        - Protocol / Crypto
        - TUN / Routing
        - Configuration parsing
        - Logging / Tracing
        - Cross-platform support
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: protocol-impact
    attributes:
      label: WireGuard Compatibility Impact
      description: Would this affect WireGuard protocol compatibility?
      options:
        - No impact (internal change only)
        - Possible impact (needs review)
        - Yes, intentional deviation
        - Unknown
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any workarounds or alternatives?
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
          required: false
