name: Platform-Specific Issue
description: Report issues specific to macOS, Linux, or Windows
title: "[Platform]: "
labels: ["platform"]
body:
  - type: markdown
    attributes:
      value: |
        Having a platform-specific issue? This could be related to TUN devices, permissions, routing, or OS integration.

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      placeholder: "macOS 14.2 Sonoma / Ubuntu 22.04 LTS / Windows 11 23H2"
    validations:
      required: true

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      options:
        - x86_64 / amd64 / Intel
        - arm64 / aarch64 / Apple Silicon
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Issue Category
      options:
        - TUN device creation
        - Route management
        - Permissions / privileges
        - Service integration (systemd/launchd)
        - DNS configuration
        - Network interface
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Describe the platform-specific issue
    validations:
      required: true

  - type: textarea
    id: setup
    attributes:
      label: Permission Setup
      description: How did you configure permissions?
      placeholder: |
        macOS: sudo ./setuid.sh
        Linux: sudo setcap cap_net_admin=eip ./minnowvpn
        Windows: Running as Administrator
    validations:
      required: false

  - type: textarea
    id: network-info
    attributes:
      label: Network Information
      description: "Output of: macOS/Linux `ifconfig` or `ip addr`, Windows `ipconfig /all`"
      render: shell
    validations:
      required: false

  - type: textarea
    id: routes
    attributes:
      label: Routing Table
      description: "Output of: macOS `netstat -rn`, Linux `ip route`, Windows `route print`"
      render: shell
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant output from running with `-v`
      render: shell
    validations:
      required: false
